apiVersion: apps.gitlab.com/v1beta1
kind: GitLab
metadata:
  name: gitlab
spec:
  chart:
#    version: "X.Y.Z" # https://gitlab.com/gitlab-org/cloud-native/gitlab-operator/-/blob/<OPERATOR_VERSION>/CHART_VERSIONS
    values:
      global:
        hosts:
          domain: lysdemolab.fr # use a real domain here
        ingress:
          configureCertmanager: true
      certmanager-issuer:
        email: jerome.armand@hpe.com # use your real email address here
